default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 54321

development:
  <<: *default
  database: my_rails_template_development

test:
  <<: *default
  database: my_rails_template_test

production:
  <<: *default
  database: my_rails_template_production
